# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:ORG}
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shui-server

useDotenv: true

plugins:
  - serverless-dotenv-plugin

provider:
  httpApi: # Use the HTTP API Gateway
    cors: true # Enable CORS for all routes
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  createPost:
    handler: functions/createPost/index.handler
    events:
      - httpApi:
          path: /createPost
          method: post

  getAllPosts:
    handler: functions/getAllPosts/index.handler
    events:
      - httpApi:
          path: /posts
          method: get

  getPost:
    handler: functions/getPost/index.handler
    events:
      - httpApi:
          path: /posts/{id}
          method: get

  getPostsByUser:
    handler: functions/getPostsByUser/index.handler
    events:
      - httpApi:
          path: /posts/username
          method: get

  updatePost:
    handler: functions/updatePost/index.handler
    events:
      - httpApi:
          path: /posts/update/{id}
          method: put

  deletePost:
    handler: functions/deletePost/index.handler
    events:
      - httpApi:
          path: /posts/delete/{id}
          method: delete

# Define the resources that this project will use. In this case, a DynamoDB table.
resources:
  Resources:
    PostDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: post-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH # Partition key
        BillingMode: PAY_PER_REQUEST
